// Package generator implements protoc-gen-jton: it emits a JTON codec per
// message that reads and writes Go struct fields directly (no protoreflect on
// the hot path), driving the core jton streaming Writer.
package generator

import (
	"strconv"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	jtonPath    = protogen.GoImportPath("github.com/birdayz/jton-go")
	ptjPath     = protogen.GoImportPath("github.com/birdayz/jton-go/protojton")
	fmtPath     = protogen.GoImportPath("fmt")
	strconvPath = protogen.GoImportPath("strconv")
	sortPath    = protogen.GoImportPath("sort")
)

// GenerateFile writes <prefix>.pb.jton.go for one proto file.
func GenerateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Messages) == 0 {
		return
	}
	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+".pb.jton.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-jton. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	for _, msg := range file.Messages {
		genMessage(g, msg)
	}
}

func genMessage(g *protogen.GeneratedFile, msg *protogen.Message) {
	if msg.Desc.IsMapEntry() {
		return
	}
	genMarshalObject(g, msg)
	if tableEligible(msg) {
		genTable(g, msg)
	}
	genUnmarshal(g, msg)
	for _, nested := range msg.Messages {
		genMessage(g, nested)
	}
}

// ── marshal: object form ────────────────────────────────────────────────────

func genMarshalObject(g *protogen.GeneratedFile, msg *protogen.Message) {
	g.P("// MarshalJTONObject writes x as a JTON object.")
	g.P("func (x *", msg.GoIdent, ") MarshalJTONObject(w *", jtonPath.Ident("Writer"), ", o ", ptjPath.Ident("MarshalOptions"), ") {")
	g.P("w.BeginObject()")
	for _, f := range msg.Fields {
		genFieldMarshal(g, f)
	}
	g.P("w.EndObject()")
	g.P("}")
	g.P()
}

func nameExpr(g *protogen.GeneratedFile, f *protogen.Field) any {
	proto := string(f.Desc.Name())
	json := f.Desc.JSONName()
	if proto == json {
		return strconv.Quote(proto)
	}
	return wrap{g.QualifiedGoIdent(ptjPath.Ident("PickName")) + "(o, " + strconv.Quote(proto) + ", " + strconv.Quote(json) + ")"}
}

// wrap lets us splice a precomputed string into g.P without extra quoting.
type wrap struct{ s string }

func (w wrap) String() string { return w.s }

func genFieldMarshal(g *protogen.GeneratedFile, f *protogen.Field) {
	// Real oneof member (not proto3 optional, which is a synthetic oneof).
	if f.Oneof != nil && !f.Oneof.Desc.IsSynthetic() {
		g.P("if v, ok := x.", f.Oneof.GoName, ".(*", f.GoIdent, "); ok {")
		g.P("w.Field(", nameExpr(g, f), ")")
		if f.Message != nil {
			g.P("v.", f.GoName, ".MarshalJTONObject(w, o)")
		} else {
			emitWrite(g, "w", f, "v."+f.GoName, false)
		}
		g.P("}")
		return
	}
	// proto3 optional (pointer field).
	if f.Desc.HasOptionalKeyword() {
		g.P("if x.", f.GoName, " != nil {")
		g.P("w.Field(", nameExpr(g, f), ")")
		emitWrite(g, "w", f, "*x."+f.GoName, false)
		g.P("}")
		return
	}
	switch {
	case f.Desc.IsMap():
		genMapMarshal(g, f)
	case f.Desc.IsList():
		g.P("if !o.OmitDefaults || len(x.", f.GoName, ") > 0 {")
		g.P("w.Field(", nameExpr(g, f), ")")
		g.P("w.BeginArray()")
		g.P("for _, e := range x.", f.GoName, " {")
		if f.Message != nil {
			g.P("e.MarshalJTONObject(w, o)")
		} else {
			emitWrite(g, "w", f, "e", false)
		}
		g.P("}")
		g.P("w.EndArray()")
		g.P("}")
	case f.Message != nil:
		g.P("if x.", f.GoName, " != nil {")
		g.P("w.Field(", nameExpr(g, f), ")")
		g.P("x.", f.GoName, ".MarshalJTONObject(w, o)")
		g.P("}")
	default:
		g.P("if !o.OmitDefaults || ", nonZero(f, "x."+f.GoName), " {")
		g.P("w.Field(", nameExpr(g, f), ")")
		emitWrite(g, "w", f, "x."+f.GoName, false)
		g.P("}")
	}
}

func genMapMarshal(g *protogen.GeneratedFile, f *protogen.Field) {
	key := f.Desc.MapKey()
	val := f.Desc.MapValue()
	g.P("if !o.OmitDefaults || len(x.", f.GoName, ") > 0 {")
	g.P("w.Field(", nameExpr(g, f), ")")
	g.P("w.BeginObject()")
	g.P("keys := make([]", mapKeyGoType(key), ", 0, len(x.", f.GoName, "))")
	g.P("for k := range x.", f.GoName, " { keys = append(keys, k) }")
	emitKeySort(g, key)
	g.P("for _, k := range keys {")
	g.P("w.Field(", mapKeyToString(g, key), ")")
	if val.Message() != nil {
		g.P("x.", f.GoName, "[k].MarshalJTONObject(w, o)")
	} else {
		emitWriteKind(g, "w", val.Kind(), nil, "x."+f.GoName+"[k]", false)
	}
	g.P("}")
	g.P("w.EndObject()")
	g.P("}")
}

// emitWrite writes a single scalar/enum value of field f from expr via recv
// ("w" Writer or "c" Cells).
func emitWrite(g *protogen.GeneratedFile, recv string, f *protogen.Field, expr string, isCell bool) {
	emitWriteKind(g, recv, f.Desc.Kind(), f, expr, isCell)
}

func emitWriteKind(g *protogen.GeneratedFile, recv string, kind protoreflect.Kind, f *protogen.Field, expr string, isCell bool) {
	switch kind {
	case protoreflect.BoolKind:
		g.P(recv, ".Bool(", expr, ")")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P(recv, ".Int(int64(", expr, "))")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P(recv, ".Int(", expr, ")")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P(recv, ".Uint(uint64(", expr, "))")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P(recv, ".Uint(", expr, ")")
	case protoreflect.FloatKind:
		g.P(recv, ".Float(float64(", expr, "))")
	case protoreflect.DoubleKind:
		g.P(recv, ".Float(", expr, ")")
	case protoreflect.StringKind:
		g.P(recv, ".String(", expr, ")")
	case protoreflect.BytesKind:
		if isCell {
			g.P(recv, ".Bytes(", expr, ")")
		} else {
			g.P(recv, ".Base64(", expr, ")")
		}
	case protoreflect.EnumKind:
		nameMap := enumNameMap(g, f, kind)
		g.P("if o.EnumsAsInts {")
		g.P(recv, ".Int(int64(", expr, "))")
		g.P("} else if nm, ok := ", nameMap, "[int32(", expr, ")]; ok {")
		g.P(recv, ".String(nm)")
		g.P("} else {")
		g.P(recv, ".Int(int64(", expr, "))")
		g.P("}")
	default:
		g.P(recv, ".Null() // unsupported kind ", kind.String())
	}
}

func enumNameMap(g *protogen.GeneratedFile, f *protogen.Field, _ protoreflect.Kind) string {
	id := f.Enum.GoIdent
	return g.QualifiedGoIdent(protogen.GoIdent{GoName: id.GoName + "_name", GoImportPath: id.GoImportPath})
}

// ── marshal: Zen Grid table form ────────────────────────────────────────────

func tableEligible(msg *protogen.Message) bool {
	if msg.Desc.IsMapEntry() || len(msg.Fields) == 0 {
		return false
	}
	for _, f := range msg.Fields {
		if f.Oneof != nil || f.Desc.IsList() || f.Desc.IsMap() || f.Message != nil || f.Desc.HasPresence() {
			return false
		}
		switch f.Desc.Kind() {
		case protoreflect.MessageKind, protoreflect.GroupKind:
			return false
		}
	}
	return true
}

func genTable(g *protogen.GeneratedFile, msg *protogen.Message) {
	g.P("// JTONTableHeaders returns the Zen Grid column names for x.")
	g.P("func (x *", msg.GoIdent, ") JTONTableHeaders(o ", ptjPath.Ident("MarshalOptions"), ") []string {")
	g.P("if o.UseJSONNames {")
	g.P("return []string{", headerList(msg, true), "}")
	g.P("}")
	g.P("return []string{", headerList(msg, false), "}")
	g.P("}")
	g.P()
	g.P("// MarshalJTONCells writes x's fields as one Zen Grid row.")
	g.P("func (x *", msg.GoIdent, ") MarshalJTONCells(c *", jtonPath.Ident("Cells"), ", o ", ptjPath.Ident("MarshalOptions"), ") {")
	for _, f := range msg.Fields {
		emitWrite(g, "c", f, "x."+f.GoName, true)
	}
	g.P("}")
	g.P()
}

func headerList(msg *protogen.Message, json bool) string {
	parts := make([]string, 0, len(msg.Fields))
	for _, f := range msg.Fields {
		n := string(f.Desc.Name())
		if json {
			n = f.Desc.JSONName()
		}
		parts = append(parts, strconv.Quote(n))
	}
	out := ""
	for i, p := range parts {
		if i > 0 {
			out += ", "
		}
		out += p
	}
	return out
}

// ── unmarshal ───────────────────────────────────────────────────────────────

func genUnmarshal(g *protogen.GeneratedFile, msg *protogen.Message) {
	g.P("// UnmarshalJTON populates x from a parsed JTON value.")
	g.P("func (x *", msg.GoIdent, ") UnmarshalJTON(v any, o ", ptjPath.Ident("UnmarshalOptions"), ") error {")
	g.P("obj, err := ", ptjPath.Ident("AsObject"), "(v)")
	g.P("if err != nil { return err }")
	g.P("for i := 0; i < obj.Len(); i++ {")
	g.P("k, fv := obj.At(i)")
	g.P("if fv == nil { continue }")
	g.P("switch k {")
	for _, f := range msg.Fields {
		g.P("case ", caseLabels(f), ":")
		genFieldUnmarshal(g, f)
	}
	g.P("default:")
	g.P("if !o.DiscardUnknown { return ", fmtPath.Ident("Errorf"), "(\"protojton: unknown field %q in ", msg.GoIdent.GoName, "\", k) }")
	g.P("}")
	g.P("}")
	g.P("return nil")
	g.P("}")
	g.P()
}

func caseLabels(f *protogen.Field) string {
	proto := strconv.Quote(string(f.Desc.Name()))
	json := strconv.Quote(f.Desc.JSONName())
	if proto == json {
		return proto
	}
	return proto + ", " + json
}

func genFieldUnmarshal(g *protogen.GeneratedFile, f *protogen.Field) {
	// Real oneof member.
	if f.Oneof != nil && !f.Oneof.Desc.IsSynthetic() {
		if f.Message != nil {
			g.P("m := &", f.Message.GoIdent, "{}")
			g.P("if err := m.UnmarshalJTON(fv, o); err != nil { return err }")
			g.P("x.", f.Oneof.GoName, " = &", f.GoIdent, "{", f.GoName, ": m}")
		} else {
			emitDecodeScalar(g, f, "val")
			g.P("x.", f.Oneof.GoName, " = &", f.GoIdent, "{", f.GoName, ": val}")
		}
		return
	}
	// proto3 optional (pointer).
	if f.Desc.HasOptionalKeyword() {
		emitDecodeScalar(g, f, "val")
		g.P("x.", f.GoName, " = &val")
		return
	}
	switch {
	case f.Desc.IsMap():
		genMapUnmarshal(g, f)
	case f.Desc.IsList():
		g.P("arr, err := ", ptjPath.Ident("AsArray"), "(fv)")
		g.P("if err != nil { return err }")
		g.P("for _, e := range arr {")
		if f.Message != nil {
			g.P("m := &", f.Message.GoIdent, "{}")
			g.P("if err := m.UnmarshalJTON(e, o); err != nil { return err }")
			g.P("x.", f.GoName, " = append(x.", f.GoName, ", m)")
		} else {
			emitDecodeScalarExpr(g, f, "e", "ev")
			g.P("x.", f.GoName, " = append(x.", f.GoName, ", ev)")
		}
		g.P("}")
	case f.Message != nil:
		g.P("if x.", f.GoName, " == nil { x.", f.GoName, " = &", f.Message.GoIdent, "{} }")
		g.P("if err := x.", f.GoName, ".UnmarshalJTON(fv, o); err != nil { return err }")
	default:
		emitDecodeScalar(g, f, "val")
		g.P("x.", f.GoName, " = val")
	}
}

// emitDecodeScalar declares `<dst>` holding fv decoded to field f's Go type.
func emitDecodeScalar(g *protogen.GeneratedFile, f *protogen.Field, dst string) {
	emitDecodeScalarExpr(g, f, "fv", dst)
}

func emitDecodeScalarExpr(g *protogen.GeneratedFile, f *protogen.Field, src, dst string) {
	emitDecodeKind(g, f.Desc.Kind(), f, src, dst)
}

func emitDecodeKind(g *protogen.GeneratedFile, kind protoreflect.Kind, f *protogen.Field, src, dst string) {
	conv := func(helper string) {
		g.P(dst, ", err := ", ptjPath.Ident(helper), "(", src, ")")
		g.P("if err != nil { return err }")
	}
	switch kind {
	case protoreflect.BoolKind:
		conv("AsBool")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		conv("AsInt32")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		conv("AsInt64")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		conv("AsUint32")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		conv("AsUint64")
	case protoreflect.FloatKind:
		conv("AsFloat32")
	case protoreflect.DoubleKind:
		conv("AsFloat64")
	case protoreflect.StringKind:
		conv("AsString")
	case protoreflect.BytesKind:
		conv("AsBytes")
	case protoreflect.EnumKind:
		valMap := enumValueMap(g, f)
		g.P("en, err := ", ptjPath.Ident("AsEnum"), "(", src, ", ", valMap, ")")
		g.P("if err != nil { return err }")
		g.P(dst, " := ", f.Enum.GoIdent, "(en)")
	default:
		g.P(dst, " := ", src, " // unsupported kind ", kind.String())
	}
}

func enumValueMap(g *protogen.GeneratedFile, f *protogen.Field) string {
	id := f.Enum.GoIdent
	return g.QualifiedGoIdent(protogen.GoIdent{GoName: id.GoName + "_value", GoImportPath: id.GoImportPath})
}

func genMapUnmarshal(g *protogen.GeneratedFile, f *protogen.Field) {
	key := f.Desc.MapKey()
	val := f.Desc.MapValue()
	g.P("mo, err := ", ptjPath.Ident("AsObject"), "(fv)")
	g.P("if err != nil { return err }")
	g.P("if x.", f.GoName, " == nil { x.", f.GoName, " = make(map[", mapKeyGoType(key), "]", mapValGoType(g, f, val), ") }")
	g.P("for j := 0; j < mo.Len(); j++ {")
	g.P("mk, mv := mo.At(j)")
	emitMapKeyDecode(g, key)
	if val.Message() != nil {
		g.P("mvv := &", f.Message.Fields[1].Message.GoIdent, "{}")
		g.P("if err := mvv.UnmarshalJTON(mv, o); err != nil { return err }")
		g.P("x.", f.GoName, "[mkey] = mvv")
	} else {
		emitDecodeKind(g, val.Kind(), nil, "mv", "mval")
		g.P("x.", f.GoName, "[mkey] = mval")
	}
	g.P("}")
}

// ── map key helpers ─────────────────────────────────────────────────────────

func mapKeyGoType(k protoreflect.FieldDescriptor) string {
	switch k.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	default:
		return "string"
	}
}

func mapValGoType(g *protogen.GeneratedFile, f *protogen.Field, v protoreflect.FieldDescriptor) any {
	if v.Message() != nil {
		return wrap{"*" + g.QualifiedGoIdent(f.Message.Fields[1].Message.GoIdent)}
	}
	switch v.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.EnumKind:
		return g.QualifiedGoIdent(f.Message.Fields[1].Enum.GoIdent)
	default:
		return "string"
	}
}

func mapKeyToString(g *protogen.GeneratedFile, k protoreflect.FieldDescriptor) any {
	switch k.Kind() {
	case protoreflect.BoolKind:
		return wrap{g.QualifiedGoIdent(strconvPath.Ident("FormatBool")) + "(k)"}
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind,
		protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return wrap{g.QualifiedGoIdent(strconvPath.Ident("FormatInt")) + "(int64(k), 10)"}
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind, protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return wrap{g.QualifiedGoIdent(strconvPath.Ident("FormatUint")) + "(uint64(k), 10)"}
	default:
		return wrap{"k"}
	}
}

func emitMapKeyDecode(g *protogen.GeneratedFile, k protoreflect.FieldDescriptor) {
	switch k.Kind() {
	case protoreflect.BoolKind:
		g.P("mkey, err := ", strconvPath.Ident("ParseBool"), "(mk)")
		g.P("if err != nil { return err }")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		g.P("mk64, err := ", strconvPath.Ident("ParseInt"), "(mk, 10, 32)")
		g.P("if err != nil { return err }")
		g.P("mkey := int32(mk64)")
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		g.P("mkey, err := ", strconvPath.Ident("ParseInt"), "(mk, 10, 64)")
		g.P("if err != nil { return err }")
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		g.P("mk64, err := ", strconvPath.Ident("ParseUint"), "(mk, 10, 32)")
		g.P("if err != nil { return err }")
		g.P("mkey := uint32(mk64)")
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		g.P("mkey, err := ", strconvPath.Ident("ParseUint"), "(mk, 10, 64)")
		g.P("if err != nil { return err }")
	default:
		g.P("mkey := mk")
	}
}

func emitKeySort(g *protogen.GeneratedFile, k protoreflect.FieldDescriptor) {
	switch k.Kind() {
	case protoreflect.StringKind:
		g.P(sortPath.Ident("Strings"), "(keys)")
	case protoreflect.BoolKind:
		g.P(sortPath.Ident("Slice"), "(keys, func(i, j int) bool { return !keys[i] && keys[j] })")
	default:
		g.P(sortPath.Ident("Slice"), "(keys, func(i, j int) bool { return keys[i] < keys[j] })")
	}
}

func nonZero(f *protogen.Field, expr string) string {
	switch f.Desc.Kind() {
	case protoreflect.BoolKind:
		return expr
	case protoreflect.StringKind:
		return expr + ` != ""`
	case protoreflect.BytesKind:
		return "len(" + expr + ") > 0"
	default:
		return expr + " != 0"
	}
}
