// Package protojton marshals protobuf messages to JTON and back. The per-message
// codec is generated by protoc-gen-jton (see ./cmd/protoc-gen-jton); this package
// is the small runtime those generated files use. There is no protoreflect on the
// encode/decode path: generated code reads and writes Go struct fields directly,
// which is why it is fast.
//
// It is a separate Go module so the protobuf dependency never reaches code that
// only needs the pure jton library. All format logic (Zen Grid framing, float
// formatting, options) lives in the core jton package; the generated code drives
// the core's streaming Writer.
package protojton

import (
	"fmt"

	"github.com/birdayz/jton-go"
	"google.golang.org/protobuf/proto"
)

// MarshalOptions configures marshaling.
type MarshalOptions struct {
	// JTON is forwarded to the core serializer (Zen Grid, delimiter, indent, …).
	JTON jton.Options
	// UseJSONNames keys objects by the field's JSON name (camelCase) instead of
	// the proto field name.
	UseJSONNames bool
	// EnumsAsInts emits enum values as numbers instead of their value names.
	EnumsAsInts bool
	// OmitDefaults drops fields holding their zero value (proto3 implicit
	// presence). Off by default so a repeated message keeps a homogeneous schema
	// for the Zen Grid.
	OmitDefaults bool
}

// UnmarshalOptions configures unmarshaling.
type UnmarshalOptions struct {
	// DiscardUnknown ignores object keys that match no field instead of erroring.
	DiscardUnknown bool
}

// Message is implemented by every message type processed by protoc-gen-jton.
type Message interface {
	proto.Message
	MarshalJTONObject(w *jton.Writer, o MarshalOptions)
	UnmarshalJTON(v any, o UnmarshalOptions) error
}

// TableMessage is additionally implemented by messages whose fields are all
// plain scalars, enabling the Zen Grid table fast path for slices of them.
type TableMessage interface {
	Message
	JTONTableHeaders(o MarshalOptions) []string
	MarshalJTONCells(c *jton.Cells, o MarshalOptions)
}

func asMessage(m proto.Message) (Message, error) {
	jm, ok := m.(Message)
	if !ok {
		return nil, fmt.Errorf("protojton: %T has no generated JTON codec; run protoc-gen-jton on its .proto", m)
	}
	return jm, nil
}

// Marshal returns the JTON encoding of m using default options.
func Marshal(m proto.Message) ([]byte, error) { return MarshalOptions{}.Marshal(m) }

// Marshal returns the JTON encoding of m.
func (o MarshalOptions) Marshal(m proto.Message) ([]byte, error) {
	jm, err := asMessage(m)
	if err != nil {
		return nil, err
	}
	w := jton.NewWriter(o.JTON)
	jm.MarshalJTONObject(w, o)
	return w.Bytes(), nil
}

// MarshalList encodes a slice of messages as a JTON array; a slice of an
// all-scalar message type becomes a Zen Grid.
func MarshalList[M proto.Message](msgs []M, opts MarshalOptions) ([]byte, error) {
	// Pre-size the output buffer from the row count to avoid repeated growth on
	// large tables (buffer reallocation showed up as ~13% of marshal time).
	w := jton.NewWriterSize(opts.JTON, 64+len(msgs)*48)
	if len(msgs) == 0 {
		w.BeginArray()
		w.EndArray()
		return w.Bytes(), nil
	}
	if _, err := asMessage(msgs[0]); err != nil {
		return nil, err
	}
	if !opts.JTON.NoZenGrid && len(msgs) >= 2 {
		if tm, ok := any(msgs[0]).(TableMessage); ok {
			headers := tm.JTONTableHeaders(opts)
			err := w.Table(headers, len(msgs), func(c *jton.Cells, i int) error {
				any(msgs[i]).(TableMessage).MarshalJTONCells(c, opts)
				return nil
			})
			return w.Bytes(), err
		}
	}
	w.BeginArray()
	for _, m := range msgs {
		any(m).(Message).MarshalJTONObject(w, opts)
	}
	w.EndArray()
	return w.Bytes(), nil
}

// Unmarshal parses JTON data into m using default options.
func Unmarshal(data []byte, m proto.Message) error { return UnmarshalOptions{}.Unmarshal(data, m) }

// Unmarshal parses JTON data into m.
func (o UnmarshalOptions) Unmarshal(data []byte, m proto.Message) error {
	jm, err := asMessage(m)
	if err != nil {
		return err
	}
	v, err := jton.Parse(data)
	if err != nil {
		return err
	}
	if v == nil {
		return nil
	}
	return jm.UnmarshalJTON(v, o)
}

// UnmarshalList parses a JTON array into messages produced by newMsg.
func UnmarshalList(data []byte, newMsg func() proto.Message, opts UnmarshalOptions) ([]proto.Message, error) {
	v, err := jton.Parse(data)
	if err != nil {
		return nil, err
	}
	arr, ok := v.([]any)
	if !ok {
		return nil, fmt.Errorf("protojton: expected a JTON array, got %T", v)
	}
	out := make([]proto.Message, len(arr))
	for i, e := range arr {
		m := newMsg()
		jm, err := asMessage(m)
		if err != nil {
			return nil, err
		}
		if err := jm.UnmarshalJTON(e, opts); err != nil {
			return nil, err
		}
		out[i] = m
	}
	return out, nil
}

// PickName returns the proto or JSON field name per the options. Generated code
// calls it for each field key.
func PickName(o MarshalOptions, protoName, jsonName string) string {
	if o.UseJSONNames {
		return jsonName
	}
	return protoName
}
