// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: test.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_COLOR_UNSPECIFIED Color = 0
	Color_RED               Color = 1
	Color_GREEN             Color = 2
	Color_BLUE              Color = 3
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_UNSPECIFIED",
		1: "RED",
		2: "GREEN",
		3: "BLUE",
	}
	Color_value = map[string]int32{
		"COLOR_UNSPECIFIED": 0,
		"RED":               1,
		"GREEN":             2,
		"BLUE":              3,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inner) Reset() {
	*x = Inner{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *Inner) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Inner) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// AllTypes exercises every proto3 field shape: all scalar kinds, enum, nested
// message, repeated scalar/message/enum, maps with scalar and message values
// and scalar keys, and a oneof.
type AllTypes struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	B        bool                   `protobuf:"varint,1,opt,name=b,proto3" json:"b,omitempty"`
	I32      int32                  `protobuf:"varint,2,opt,name=i32,proto3" json:"i32,omitempty"`
	I64      int64                  `protobuf:"varint,3,opt,name=i64,proto3" json:"i64,omitempty"`
	U32      uint32                 `protobuf:"varint,4,opt,name=u32,proto3" json:"u32,omitempty"`
	U64      uint64                 `protobuf:"varint,5,opt,name=u64,proto3" json:"u64,omitempty"`
	S32      int32                  `protobuf:"zigzag32,6,opt,name=s32,proto3" json:"s32,omitempty"`
	S64      int64                  `protobuf:"zigzag64,7,opt,name=s64,proto3" json:"s64,omitempty"`
	F32      uint32                 `protobuf:"fixed32,8,opt,name=f32,proto3" json:"f32,omitempty"`
	F64      uint64                 `protobuf:"fixed64,9,opt,name=f64,proto3" json:"f64,omitempty"`
	Sf32     int32                  `protobuf:"fixed32,10,opt,name=sf32,proto3" json:"sf32,omitempty"`
	Sf64     int64                  `protobuf:"fixed64,11,opt,name=sf64,proto3" json:"sf64,omitempty"`
	Fl       float32                `protobuf:"fixed32,12,opt,name=fl,proto3" json:"fl,omitempty"`
	Db       float64                `protobuf:"fixed64,13,opt,name=db,proto3" json:"db,omitempty"`
	Str      string                 `protobuf:"bytes,14,opt,name=str,proto3" json:"str,omitempty"`
	By       []byte                 `protobuf:"bytes,15,opt,name=by,proto3" json:"by,omitempty"`
	Color    Color                  `protobuf:"varint,16,opt,name=color,proto3,enum=testpb.Color" json:"color,omitempty"`
	Inner    *Inner                 `protobuf:"bytes,17,opt,name=inner,proto3" json:"inner,omitempty"`
	RepI32   []int32                `protobuf:"varint,18,rep,packed,name=rep_i32,json=repI32,proto3" json:"rep_i32,omitempty"`
	RepStr   []string               `protobuf:"bytes,19,rep,name=rep_str,json=repStr,proto3" json:"rep_str,omitempty"`
	RepInner []*Inner               `protobuf:"bytes,20,rep,name=rep_inner,json=repInner,proto3" json:"rep_inner,omitempty"`
	MapSi    map[string]int32       `protobuf:"bytes,21,rep,name=map_si,json=mapSi,proto3" json:"map_si,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	MapIs    map[int32]string       `protobuf:"bytes,22,rep,name=map_is,json=mapIs,proto3" json:"map_is,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapSmsg  map[string]*Inner      `protobuf:"bytes,23,rep,name=map_smsg,json=mapSmsg,proto3" json:"map_smsg,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Types that are valid to be assigned to Choice:
	//
	//	*AllTypes_ChoiceStr
	//	*AllTypes_ChoiceInt
	//	*AllTypes_ChoiceMsg
	Choice        isAllTypes_Choice `protobuf_oneof:"choice"`
	RepEnum       []Color           `protobuf:"varint,27,rep,packed,name=rep_enum,json=repEnum,proto3,enum=testpb.Color" json:"rep_enum,omitempty"`
	OptI32        *int32            `protobuf:"varint,28,opt,name=opt_i32,json=optI32,proto3,oneof" json:"opt_i32,omitempty"` // explicit presence
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTypes) Reset() {
	*x = AllTypes{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTypes) ProtoMessage() {}

func (x *AllTypes) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTypes.ProtoReflect.Descriptor instead.
func (*AllTypes) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *AllTypes) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *AllTypes) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *AllTypes) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *AllTypes) GetU32() uint32 {
	if x != nil {
		return x.U32
	}
	return 0
}

func (x *AllTypes) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

func (x *AllTypes) GetS32() int32 {
	if x != nil {
		return x.S32
	}
	return 0
}

func (x *AllTypes) GetS64() int64 {
	if x != nil {
		return x.S64
	}
	return 0
}

func (x *AllTypes) GetF32() uint32 {
	if x != nil {
		return x.F32
	}
	return 0
}

func (x *AllTypes) GetF64() uint64 {
	if x != nil {
		return x.F64
	}
	return 0
}

func (x *AllTypes) GetSf32() int32 {
	if x != nil {
		return x.Sf32
	}
	return 0
}

func (x *AllTypes) GetSf64() int64 {
	if x != nil {
		return x.Sf64
	}
	return 0
}

func (x *AllTypes) GetFl() float32 {
	if x != nil {
		return x.Fl
	}
	return 0
}

func (x *AllTypes) GetDb() float64 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *AllTypes) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *AllTypes) GetBy() []byte {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *AllTypes) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_COLOR_UNSPECIFIED
}

func (x *AllTypes) GetInner() *Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *AllTypes) GetRepI32() []int32 {
	if x != nil {
		return x.RepI32
	}
	return nil
}

func (x *AllTypes) GetRepStr() []string {
	if x != nil {
		return x.RepStr
	}
	return nil
}

func (x *AllTypes) GetRepInner() []*Inner {
	if x != nil {
		return x.RepInner
	}
	return nil
}

func (x *AllTypes) GetMapSi() map[string]int32 {
	if x != nil {
		return x.MapSi
	}
	return nil
}

func (x *AllTypes) GetMapIs() map[int32]string {
	if x != nil {
		return x.MapIs
	}
	return nil
}

func (x *AllTypes) GetMapSmsg() map[string]*Inner {
	if x != nil {
		return x.MapSmsg
	}
	return nil
}

func (x *AllTypes) GetChoice() isAllTypes_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *AllTypes) GetChoiceStr() string {
	if x != nil {
		if x, ok := x.Choice.(*AllTypes_ChoiceStr); ok {
			return x.ChoiceStr
		}
	}
	return ""
}

func (x *AllTypes) GetChoiceInt() int32 {
	if x != nil {
		if x, ok := x.Choice.(*AllTypes_ChoiceInt); ok {
			return x.ChoiceInt
		}
	}
	return 0
}

func (x *AllTypes) GetChoiceMsg() *Inner {
	if x != nil {
		if x, ok := x.Choice.(*AllTypes_ChoiceMsg); ok {
			return x.ChoiceMsg
		}
	}
	return nil
}

func (x *AllTypes) GetRepEnum() []Color {
	if x != nil {
		return x.RepEnum
	}
	return nil
}

func (x *AllTypes) GetOptI32() int32 {
	if x != nil && x.OptI32 != nil {
		return *x.OptI32
	}
	return 0
}

type isAllTypes_Choice interface {
	isAllTypes_Choice()
}

type AllTypes_ChoiceStr struct {
	ChoiceStr string `protobuf:"bytes,24,opt,name=choice_str,json=choiceStr,proto3,oneof"`
}

type AllTypes_ChoiceInt struct {
	ChoiceInt int32 `protobuf:"varint,25,opt,name=choice_int,json=choiceInt,proto3,oneof"`
}

type AllTypes_ChoiceMsg struct {
	ChoiceMsg *Inner `protobuf:"bytes,26,opt,name=choice_msg,json=choiceMsg,proto3,oneof"`
}

func (*AllTypes_ChoiceStr) isAllTypes_Choice() {}

func (*AllTypes_ChoiceInt) isAllTypes_Choice() {}

func (*AllTypes_ChoiceMsg) isAllTypes_Choice() {}

// Row is an all-scalar message, the shape the Zen Grid is built for.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Dept          string                 `protobuf:"bytes,3,opt,name=dept,proto3" json:"dept,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Active        bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Row) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Row) GetDept() string {
	if x != nil {
		return x.Dept
	}
	return ""
}

func (x *Row) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Row) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x06testpb\"-\n" +
	"\x05Inner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xeb\a\n" +
	"\bAllTypes\x12\f\n" +
	"\x01b\x18\x01 \x01(\bR\x01b\x12\x10\n" +
	"\x03i32\x18\x02 \x01(\x05R\x03i32\x12\x10\n" +
	"\x03i64\x18\x03 \x01(\x03R\x03i64\x12\x10\n" +
	"\x03u32\x18\x04 \x01(\rR\x03u32\x12\x10\n" +
	"\x03u64\x18\x05 \x01(\x04R\x03u64\x12\x10\n" +
	"\x03s32\x18\x06 \x01(\x11R\x03s32\x12\x10\n" +
	"\x03s64\x18\a \x01(\x12R\x03s64\x12\x10\n" +
	"\x03f32\x18\b \x01(\aR\x03f32\x12\x10\n" +
	"\x03f64\x18\t \x01(\x06R\x03f64\x12\x12\n" +
	"\x04sf32\x18\n" +
	" \x01(\x0fR\x04sf32\x12\x12\n" +
	"\x04sf64\x18\v \x01(\x10R\x04sf64\x12\x0e\n" +
	"\x02fl\x18\f \x01(\x02R\x02fl\x12\x0e\n" +
	"\x02db\x18\r \x01(\x01R\x02db\x12\x10\n" +
	"\x03str\x18\x0e \x01(\tR\x03str\x12\x0e\n" +
	"\x02by\x18\x0f \x01(\fR\x02by\x12#\n" +
	"\x05color\x18\x10 \x01(\x0e2\r.testpb.ColorR\x05color\x12#\n" +
	"\x05inner\x18\x11 \x01(\v2\r.testpb.InnerR\x05inner\x12\x17\n" +
	"\arep_i32\x18\x12 \x03(\x05R\x06repI32\x12\x17\n" +
	"\arep_str\x18\x13 \x03(\tR\x06repStr\x12*\n" +
	"\trep_inner\x18\x14 \x03(\v2\r.testpb.InnerR\brepInner\x122\n" +
	"\x06map_si\x18\x15 \x03(\v2\x1b.testpb.AllTypes.MapSiEntryR\x05mapSi\x122\n" +
	"\x06map_is\x18\x16 \x03(\v2\x1b.testpb.AllTypes.MapIsEntryR\x05mapIs\x128\n" +
	"\bmap_smsg\x18\x17 \x03(\v2\x1d.testpb.AllTypes.MapSmsgEntryR\amapSmsg\x12\x1f\n" +
	"\n" +
	"choice_str\x18\x18 \x01(\tH\x00R\tchoiceStr\x12\x1f\n" +
	"\n" +
	"choice_int\x18\x19 \x01(\x05H\x00R\tchoiceInt\x12.\n" +
	"\n" +
	"choice_msg\x18\x1a \x01(\v2\r.testpb.InnerH\x00R\tchoiceMsg\x12(\n" +
	"\brep_enum\x18\x1b \x03(\x0e2\r.testpb.ColorR\arepEnum\x12\x1c\n" +
	"\aopt_i32\x18\x1c \x01(\x05H\x01R\x06optI32\x88\x01\x01\x1a8\n" +
	"\n" +
	"MapSiEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a8\n" +
	"\n" +
	"MapIsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aI\n" +
	"\fMapSmsgEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.testpb.InnerR\x05value:\x028\x01B\b\n" +
	"\x06choiceB\n" +
	"\n" +
	"\b_opt_i32\"k\n" +
	"\x03Row\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04dept\x18\x03 \x01(\tR\x04dept\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active*<\n" +
	"\x05Color\x12\x15\n" +
	"\x11COLOR_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03RED\x10\x01\x12\t\n" +
	"\x05GREEN\x10\x02\x12\b\n" +
	"\x04BLUE\x10\x03B6Z4github.com/birdayz/jton-go/protojton/internal/testpbb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_test_proto_goTypes = []any{
	(Color)(0),       // 0: testpb.Color
	(*Inner)(nil),    // 1: testpb.Inner
	(*AllTypes)(nil), // 2: testpb.AllTypes
	(*Row)(nil),      // 3: testpb.Row
	nil,              // 4: testpb.AllTypes.MapSiEntry
	nil,              // 5: testpb.AllTypes.MapIsEntry
	nil,              // 6: testpb.AllTypes.MapSmsgEntry
}
var file_test_proto_depIdxs = []int32{
	0, // 0: testpb.AllTypes.color:type_name -> testpb.Color
	1, // 1: testpb.AllTypes.inner:type_name -> testpb.Inner
	1, // 2: testpb.AllTypes.rep_inner:type_name -> testpb.Inner
	4, // 3: testpb.AllTypes.map_si:type_name -> testpb.AllTypes.MapSiEntry
	5, // 4: testpb.AllTypes.map_is:type_name -> testpb.AllTypes.MapIsEntry
	6, // 5: testpb.AllTypes.map_smsg:type_name -> testpb.AllTypes.MapSmsgEntry
	1, // 6: testpb.AllTypes.choice_msg:type_name -> testpb.Inner
	0, // 7: testpb.AllTypes.rep_enum:type_name -> testpb.Color
	1, // 8: testpb.AllTypes.MapSmsgEntry.value:type_name -> testpb.Inner
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[1].OneofWrappers = []any{
		(*AllTypes_ChoiceStr)(nil),
		(*AllTypes_ChoiceInt)(nil),
		(*AllTypes_ChoiceMsg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
