// Code generated by protoc-gen-jton. DO NOT EDIT.
// source: test.proto

package testpb

import (
	fmt "fmt"
	jton_go "github.com/birdayz/jton-go"
	protojton "github.com/birdayz/jton-go/protojton"
	sort "sort"
	strconv "strconv"
)

// MarshalJTONObject writes x as a JTON object.
func (x *Inner) MarshalJTONObject(w *jton_go.Writer, o protojton.MarshalOptions) {
	w.BeginObject()
	if !o.OmitDefaults || x.Id != 0 {
		w.Field("id")
		w.Int(int64(x.Id))
	}
	if !o.OmitDefaults || x.Label != "" {
		w.Field("label")
		w.String(x.Label)
	}
	w.EndObject()
}

// JTONTableHeaders returns the Zen Grid column names for x.
func (x *Inner) JTONTableHeaders(o protojton.MarshalOptions) []string {
	if o.UseJSONNames {
		return []string{"id", "label"}
	}
	return []string{"id", "label"}
}

// MarshalJTONCells writes x's fields as one Zen Grid row.
func (x *Inner) MarshalJTONCells(c *jton_go.Cells, o protojton.MarshalOptions) {
	c.Int(int64(x.Id))
	c.String(x.Label)
}

// UnmarshalJTON populates x from a parsed JTON value.
func (x *Inner) UnmarshalJTON(v any, o protojton.UnmarshalOptions) error {
	obj, err := protojton.AsObject(v)
	if err != nil {
		return err
	}
	for i := 0; i < obj.Len(); i++ {
		k, fv := obj.At(i)
		if fv == nil {
			continue
		}
		switch k {
		case "id":
			val, err := protojton.AsInt32(fv)
			if err != nil {
				return err
			}
			x.Id = val
		case "label":
			val, err := protojton.AsString(fv)
			if err != nil {
				return err
			}
			x.Label = val
		default:
			if !o.DiscardUnknown {
				return fmt.Errorf("protojton: unknown field %q in Inner", k)
			}
		}
	}
	return nil
}

// MarshalJTONObject writes x as a JTON object.
func (x *AllTypes) MarshalJTONObject(w *jton_go.Writer, o protojton.MarshalOptions) {
	w.BeginObject()
	if !o.OmitDefaults || x.B {
		w.Field("b")
		w.Bool(x.B)
	}
	if !o.OmitDefaults || x.I32 != 0 {
		w.Field("i32")
		w.Int(int64(x.I32))
	}
	if !o.OmitDefaults || x.I64 != 0 {
		w.Field("i64")
		w.Int(x.I64)
	}
	if !o.OmitDefaults || x.U32 != 0 {
		w.Field("u32")
		w.Uint(uint64(x.U32))
	}
	if !o.OmitDefaults || x.U64 != 0 {
		w.Field("u64")
		w.Uint(x.U64)
	}
	if !o.OmitDefaults || x.S32 != 0 {
		w.Field("s32")
		w.Int(int64(x.S32))
	}
	if !o.OmitDefaults || x.S64 != 0 {
		w.Field("s64")
		w.Int(x.S64)
	}
	if !o.OmitDefaults || x.F32 != 0 {
		w.Field("f32")
		w.Uint(uint64(x.F32))
	}
	if !o.OmitDefaults || x.F64 != 0 {
		w.Field("f64")
		w.Uint(x.F64)
	}
	if !o.OmitDefaults || x.Sf32 != 0 {
		w.Field("sf32")
		w.Int(int64(x.Sf32))
	}
	if !o.OmitDefaults || x.Sf64 != 0 {
		w.Field("sf64")
		w.Int(x.Sf64)
	}
	if !o.OmitDefaults || x.Fl != 0 {
		w.Field("fl")
		w.Float(float64(x.Fl))
	}
	if !o.OmitDefaults || x.Db != 0 {
		w.Field("db")
		w.Float(x.Db)
	}
	if !o.OmitDefaults || x.Str != "" {
		w.Field("str")
		w.String(x.Str)
	}
	if !o.OmitDefaults || len(x.By) > 0 {
		w.Field("by")
		w.Base64(x.By)
	}
	if !o.OmitDefaults || x.Color != 0 {
		w.Field("color")
		if o.EnumsAsInts {
			w.Int(int64(x.Color))
		} else if nm, ok := Color_name[int32(x.Color)]; ok {
			w.String(nm)
		} else {
			w.Int(int64(x.Color))
		}
	}
	if x.Inner != nil {
		w.Field("inner")
		x.Inner.MarshalJTONObject(w, o)
	}
	if !o.OmitDefaults || len(x.RepI32) > 0 {
		w.Field(protojton.PickName(o, "rep_i32", "repI32"))
		w.BeginArray()
		for _, e := range x.RepI32 {
			w.Int(int64(e))
		}
		w.EndArray()
	}
	if !o.OmitDefaults || len(x.RepStr) > 0 {
		w.Field(protojton.PickName(o, "rep_str", "repStr"))
		w.BeginArray()
		for _, e := range x.RepStr {
			w.String(e)
		}
		w.EndArray()
	}
	if !o.OmitDefaults || len(x.RepInner) > 0 {
		w.Field(protojton.PickName(o, "rep_inner", "repInner"))
		w.BeginArray()
		for _, e := range x.RepInner {
			e.MarshalJTONObject(w, o)
		}
		w.EndArray()
	}
	if !o.OmitDefaults || len(x.MapSi) > 0 {
		w.Field(protojton.PickName(o, "map_si", "mapSi"))
		w.BeginObject()
		keys := make([]string, 0, len(x.MapSi))
		for k := range x.MapSi {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			w.Field(k)
			w.Int(int64(x.MapSi[k]))
		}
		w.EndObject()
	}
	if !o.OmitDefaults || len(x.MapIs) > 0 {
		w.Field(protojton.PickName(o, "map_is", "mapIs"))
		w.BeginObject()
		keys := make([]int32, 0, len(x.MapIs))
		for k := range x.MapIs {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		for _, k := range keys {
			w.Field(strconv.FormatInt(int64(k), 10))
			w.String(x.MapIs[k])
		}
		w.EndObject()
	}
	if !o.OmitDefaults || len(x.MapSmsg) > 0 {
		w.Field(protojton.PickName(o, "map_smsg", "mapSmsg"))
		w.BeginObject()
		keys := make([]string, 0, len(x.MapSmsg))
		for k := range x.MapSmsg {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			w.Field(k)
			x.MapSmsg[k].MarshalJTONObject(w, o)
		}
		w.EndObject()
	}
	if v, ok := x.Choice.(*AllTypes_ChoiceStr); ok {
		w.Field(protojton.PickName(o, "choice_str", "choiceStr"))
		w.String(v.ChoiceStr)
	}
	if v, ok := x.Choice.(*AllTypes_ChoiceInt); ok {
		w.Field(protojton.PickName(o, "choice_int", "choiceInt"))
		w.Int(int64(v.ChoiceInt))
	}
	if v, ok := x.Choice.(*AllTypes_ChoiceMsg); ok {
		w.Field(protojton.PickName(o, "choice_msg", "choiceMsg"))
		v.ChoiceMsg.MarshalJTONObject(w, o)
	}
	if !o.OmitDefaults || len(x.RepEnum) > 0 {
		w.Field(protojton.PickName(o, "rep_enum", "repEnum"))
		w.BeginArray()
		for _, e := range x.RepEnum {
			if o.EnumsAsInts {
				w.Int(int64(e))
			} else if nm, ok := Color_name[int32(e)]; ok {
				w.String(nm)
			} else {
				w.Int(int64(e))
			}
		}
		w.EndArray()
	}
	if x.OptI32 != nil {
		w.Field(protojton.PickName(o, "opt_i32", "optI32"))
		w.Int(int64(*x.OptI32))
	}
	w.EndObject()
}

// UnmarshalJTON populates x from a parsed JTON value.
func (x *AllTypes) UnmarshalJTON(v any, o protojton.UnmarshalOptions) error {
	obj, err := protojton.AsObject(v)
	if err != nil {
		return err
	}
	for i := 0; i < obj.Len(); i++ {
		k, fv := obj.At(i)
		if fv == nil {
			continue
		}
		switch k {
		case "b":
			val, err := protojton.AsBool(fv)
			if err != nil {
				return err
			}
			x.B = val
		case "i32":
			val, err := protojton.AsInt32(fv)
			if err != nil {
				return err
			}
			x.I32 = val
		case "i64":
			val, err := protojton.AsInt64(fv)
			if err != nil {
				return err
			}
			x.I64 = val
		case "u32":
			val, err := protojton.AsUint32(fv)
			if err != nil {
				return err
			}
			x.U32 = val
		case "u64":
			val, err := protojton.AsUint64(fv)
			if err != nil {
				return err
			}
			x.U64 = val
		case "s32":
			val, err := protojton.AsInt32(fv)
			if err != nil {
				return err
			}
			x.S32 = val
		case "s64":
			val, err := protojton.AsInt64(fv)
			if err != nil {
				return err
			}
			x.S64 = val
		case "f32":
			val, err := protojton.AsUint32(fv)
			if err != nil {
				return err
			}
			x.F32 = val
		case "f64":
			val, err := protojton.AsUint64(fv)
			if err != nil {
				return err
			}
			x.F64 = val
		case "sf32":
			val, err := protojton.AsInt32(fv)
			if err != nil {
				return err
			}
			x.Sf32 = val
		case "sf64":
			val, err := protojton.AsInt64(fv)
			if err != nil {
				return err
			}
			x.Sf64 = val
		case "fl":
			val, err := protojton.AsFloat32(fv)
			if err != nil {
				return err
			}
			x.Fl = val
		case "db":
			val, err := protojton.AsFloat64(fv)
			if err != nil {
				return err
			}
			x.Db = val
		case "str":
			val, err := protojton.AsString(fv)
			if err != nil {
				return err
			}
			x.Str = val
		case "by":
			val, err := protojton.AsBytes(fv)
			if err != nil {
				return err
			}
			x.By = val
		case "color":
			en, err := protojton.AsEnum(fv, Color_value)
			if err != nil {
				return err
			}
			val := Color(en)
			x.Color = val
		case "inner":
			if x.Inner == nil {
				x.Inner = &Inner{}
			}
			if err := x.Inner.UnmarshalJTON(fv, o); err != nil {
				return err
			}
		case "rep_i32", "repI32":
			arr, err := protojton.AsArray(fv)
			if err != nil {
				return err
			}
			for _, e := range arr {
				ev, err := protojton.AsInt32(e)
				if err != nil {
					return err
				}
				x.RepI32 = append(x.RepI32, ev)
			}
		case "rep_str", "repStr":
			arr, err := protojton.AsArray(fv)
			if err != nil {
				return err
			}
			for _, e := range arr {
				ev, err := protojton.AsString(e)
				if err != nil {
					return err
				}
				x.RepStr = append(x.RepStr, ev)
			}
		case "rep_inner", "repInner":
			arr, err := protojton.AsArray(fv)
			if err != nil {
				return err
			}
			for _, e := range arr {
				m := &Inner{}
				if err := m.UnmarshalJTON(e, o); err != nil {
					return err
				}
				x.RepInner = append(x.RepInner, m)
			}
		case "map_si", "mapSi":
			mo, err := protojton.AsObject(fv)
			if err != nil {
				return err
			}
			if x.MapSi == nil {
				x.MapSi = make(map[string]int32)
			}
			for j := 0; j < mo.Len(); j++ {
				mk, mv := mo.At(j)
				mkey := mk
				mval, err := protojton.AsInt32(mv)
				if err != nil {
					return err
				}
				x.MapSi[mkey] = mval
			}
		case "map_is", "mapIs":
			mo, err := protojton.AsObject(fv)
			if err != nil {
				return err
			}
			if x.MapIs == nil {
				x.MapIs = make(map[int32]string)
			}
			for j := 0; j < mo.Len(); j++ {
				mk, mv := mo.At(j)
				mk64, err := strconv.ParseInt(mk, 10, 32)
				if err != nil {
					return err
				}
				mkey := int32(mk64)
				mval, err := protojton.AsString(mv)
				if err != nil {
					return err
				}
				x.MapIs[mkey] = mval
			}
		case "map_smsg", "mapSmsg":
			mo, err := protojton.AsObject(fv)
			if err != nil {
				return err
			}
			if x.MapSmsg == nil {
				x.MapSmsg = make(map[string]*Inner)
			}
			for j := 0; j < mo.Len(); j++ {
				mk, mv := mo.At(j)
				mkey := mk
				mvv := &Inner{}
				if err := mvv.UnmarshalJTON(mv, o); err != nil {
					return err
				}
				x.MapSmsg[mkey] = mvv
			}
		case "choice_str", "choiceStr":
			val, err := protojton.AsString(fv)
			if err != nil {
				return err
			}
			x.Choice = &AllTypes_ChoiceStr{ChoiceStr: val}
		case "choice_int", "choiceInt":
			val, err := protojton.AsInt32(fv)
			if err != nil {
				return err
			}
			x.Choice = &AllTypes_ChoiceInt{ChoiceInt: val}
		case "choice_msg", "choiceMsg":
			m := &Inner{}
			if err := m.UnmarshalJTON(fv, o); err != nil {
				return err
			}
			x.Choice = &AllTypes_ChoiceMsg{ChoiceMsg: m}
		case "rep_enum", "repEnum":
			arr, err := protojton.AsArray(fv)
			if err != nil {
				return err
			}
			for _, e := range arr {
				en, err := protojton.AsEnum(e, Color_value)
				if err != nil {
					return err
				}
				ev := Color(en)
				x.RepEnum = append(x.RepEnum, ev)
			}
		case "opt_i32", "optI32":
			val, err := protojton.AsInt32(fv)
			if err != nil {
				return err
			}
			x.OptI32 = &val
		default:
			if !o.DiscardUnknown {
				return fmt.Errorf("protojton: unknown field %q in AllTypes", k)
			}
		}
	}
	return nil
}

// MarshalJTONObject writes x as a JTON object.
func (x *Row) MarshalJTONObject(w *jton_go.Writer, o protojton.MarshalOptions) {
	w.BeginObject()
	if !o.OmitDefaults || x.Id != 0 {
		w.Field("id")
		w.Int(x.Id)
	}
	if !o.OmitDefaults || x.Name != "" {
		w.Field("name")
		w.String(x.Name)
	}
	if !o.OmitDefaults || x.Dept != "" {
		w.Field("dept")
		w.String(x.Dept)
	}
	if !o.OmitDefaults || x.Score != 0 {
		w.Field("score")
		w.Float(x.Score)
	}
	if !o.OmitDefaults || x.Active {
		w.Field("active")
		w.Bool(x.Active)
	}
	w.EndObject()
}

// JTONTableHeaders returns the Zen Grid column names for x.
func (x *Row) JTONTableHeaders(o protojton.MarshalOptions) []string {
	if o.UseJSONNames {
		return []string{"id", "name", "dept", "score", "active"}
	}
	return []string{"id", "name", "dept", "score", "active"}
}

// MarshalJTONCells writes x's fields as one Zen Grid row.
func (x *Row) MarshalJTONCells(c *jton_go.Cells, o protojton.MarshalOptions) {
	c.Int(x.Id)
	c.String(x.Name)
	c.String(x.Dept)
	c.Float(x.Score)
	c.Bool(x.Active)
}

// UnmarshalJTON populates x from a parsed JTON value.
func (x *Row) UnmarshalJTON(v any, o protojton.UnmarshalOptions) error {
	obj, err := protojton.AsObject(v)
	if err != nil {
		return err
	}
	for i := 0; i < obj.Len(); i++ {
		k, fv := obj.At(i)
		if fv == nil {
			continue
		}
		switch k {
		case "id":
			val, err := protojton.AsInt64(fv)
			if err != nil {
				return err
			}
			x.Id = val
		case "name":
			val, err := protojton.AsString(fv)
			if err != nil {
				return err
			}
			x.Name = val
		case "dept":
			val, err := protojton.AsString(fv)
			if err != nil {
				return err
			}
			x.Dept = val
		case "score":
			val, err := protojton.AsFloat64(fv)
			if err != nil {
				return err
			}
			x.Score = val
		case "active":
			val, err := protojton.AsBool(fv)
			if err != nil {
				return err
			}
			x.Active = val
		default:
			if !o.DiscardUnknown {
				return fmt.Errorf("protojton: unknown field %q in Row", k)
			}
		}
	}
	return nil
}
